// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: PingPuppy

#ifndef UI_SCREENMAIN_H
#define UI_SCREENMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMain
extern void ui_ScreenMain_screen_init(void);
extern void ui_ScreenMain_screen_destroy(void);
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_ImagePuppy;
extern lv_obj_t * ui_ImageWifi1;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_ImageWifi2;
extern lv_obj_t * ui_ImageWifi3;
extern lv_obj_t * ui_ImageWifi4;
extern lv_obj_t * ui_ImageWifi5;
extern lv_obj_t * ui_LabelStatus;
extern lv_obj_t * ui_LabelWifi;
extern lv_obj_t * ui_LabelTOD;
extern lv_obj_t * ui_LabelDT;
extern lv_obj_t * ui_LabelOverall;
extern lv_obj_t * ui_Label18;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

