// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: PingPuppy

#include "../ui.h"

lv_obj_t * ui_ScreenMain = NULL;
lv_obj_t * ui_ImagePuppy = NULL;
lv_obj_t * ui_ImageWifi1 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_ImageWifi2 = NULL;
lv_obj_t * ui_ImageWifi3 = NULL;
lv_obj_t * ui_ImageWifi4 = NULL;
lv_obj_t * ui_ImageWifi5 = NULL;
lv_obj_t * ui_LabelStatus = NULL;
lv_obj_t * ui_LabelWifi = NULL;
lv_obj_t * ui_LabelTOD = NULL;
lv_obj_t * ui_LabelDT = NULL;
lv_obj_t * ui_LabelOverall = NULL;
lv_obj_t * ui_Label18 = NULL;
// event funtions
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenSettings_screen_init);
    }
}

// build funtions

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImagePuppy = lv_image_create(ui_ScreenMain);
    lv_image_set_src(ui_ImagePuppy, &ui_img_pingpuppysmall_png);
    lv_obj_set_width(ui_ImagePuppy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePuppy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImagePuppy, -116);
    lv_obj_set_y(ui_ImagePuppy, -46);
    lv_obj_set_align(ui_ImagePuppy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagePuppy, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImagePuppy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWifi1 = lv_image_create(ui_ScreenMain);
    lv_image_set_src(ui_ImageWifi1, &ui_img_wifi1_png);
    lv_obj_set_width(ui_ImageWifi1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWifi1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWifi1, 139);
    lv_obj_set_y(ui_ImageWifi1, -84);
    lv_obj_set_align(ui_ImageWifi1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWifi1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageWifi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button6 = lv_button_create(ui_ScreenMain);
    lv_obj_set_width(ui_Button6, 100);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_x(ui_Button6, 0);
    lv_obj_set_y(ui_Button6, 90);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Settings");

    ui_ImageWifi2 = lv_image_create(ui_ScreenMain);
    lv_image_set_src(ui_ImageWifi2, &ui_img_wifi2_png);
    lv_obj_set_width(ui_ImageWifi2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWifi2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWifi2, 140);
    lv_obj_set_y(ui_ImageWifi2, -100);
    lv_obj_set_align(ui_ImageWifi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWifi2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageWifi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWifi3 = lv_image_create(ui_ScreenMain);
    lv_image_set_src(ui_ImageWifi3, &ui_img_wifi3_png);
    lv_obj_set_width(ui_ImageWifi3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWifi3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWifi3, 140);
    lv_obj_set_y(ui_ImageWifi3, -100);
    lv_obj_set_align(ui_ImageWifi3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWifi3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageWifi3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWifi4 = lv_image_create(ui_ScreenMain);
    lv_image_set_src(ui_ImageWifi4, &ui_img_wifi4_png);
    lv_obj_set_width(ui_ImageWifi4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWifi4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWifi4, 140);
    lv_obj_set_y(ui_ImageWifi4, -100);
    lv_obj_set_align(ui_ImageWifi4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWifi4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageWifi4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWifi5 = lv_image_create(ui_ScreenMain);
    lv_image_set_src(ui_ImageWifi5, &ui_img_wifi5_png);
    lv_obj_set_width(ui_ImageWifi5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWifi5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWifi5, 140);
    lv_obj_set_y(ui_ImageWifi5, -100);
    lv_obj_set_align(ui_ImageWifi5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWifi5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageWifi5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelStatus = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStatus, -1);
    lv_obj_set_y(ui_LabelStatus, -14);
    lv_obj_set_align(ui_LabelStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStatus, "status");

    ui_LabelWifi = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWifi, 0);
    lv_obj_set_y(ui_LabelWifi, -88);
    lv_obj_set_align(ui_LabelWifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWifi, "WiFi Signal Strength: ");

    ui_LabelTOD = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelTOD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTOD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTOD, 0);
    lv_obj_set_y(ui_LabelTOD, -44);
    lv_obj_set_align(ui_LabelTOD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTOD, "00:00:00");

    ui_LabelDT = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelDT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDT, 0);
    lv_obj_set_y(ui_LabelDT, -65);
    lv_obj_set_align(ui_LabelDT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDT, "Date / Time");

    ui_LabelOverall = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_LabelOverall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOverall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOverall, 0);
    lv_obj_set_y(ui_LabelOverall, 33);
    lv_obj_set_align(ui_LabelOverall, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelOverall, " OK ");
    lv_obj_set_style_text_font(ui_LabelOverall, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelOverall, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelOverall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_ScreenMain);
    lv_obj_set_height(ui_Label18, 20);
    lv_obj_set_width(ui_Label18, lv_pct(100));
    lv_obj_set_x(ui_Label18, 0);
    lv_obj_set_y(ui_Label18, -110);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "        PingPuppy Network Health Monitor");
    lv_obj_set_style_bg_color(ui_Label18, lv_color_hex(0x60FFE9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);

}

void ui_ScreenMain_screen_destroy(void)
{
    if(ui_ScreenMain) lv_obj_del(ui_ScreenMain);

    // NULL screen variables
    ui_ScreenMain = NULL;
    ui_ImagePuppy = NULL;
    ui_ImageWifi1 = NULL;
    ui_Button6 = NULL;
    ui_Label13 = NULL;
    ui_ImageWifi2 = NULL;
    ui_ImageWifi3 = NULL;
    ui_ImageWifi4 = NULL;
    ui_ImageWifi5 = NULL;
    ui_LabelStatus = NULL;
    ui_LabelWifi = NULL;
    ui_LabelTOD = NULL;
    ui_LabelDT = NULL;
    ui_LabelOverall = NULL;
    ui_Label18 = NULL;

}
