// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: PingPuppy

#include "../ui.h"

lv_obj_t * ui_ScreenSettings = NULL;
lv_obj_t * ui_TabViewSettings = NULL;
lv_obj_t * ui_TabPageWifi = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_DropdownSSID = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_ButtonScan = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_TextAreaPassword = NULL;
lv_obj_t * ui_ButtonTestConnection = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_TabPageHosts = NULL;
lv_obj_t * ui_TextAreaHost1 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_ButtonTest1 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_TextAreaHost2 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_ButtonTest2 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_TextAreaHost3 = NULL;
lv_obj_t * ui_ButtonTest3 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_TabPageActions = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_DropdownReboot = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_DropdownPing = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_TabPageTest = NULL;
lv_obj_t * ui_CheckboxRelay1 = NULL;
lv_obj_t * ui_CheckboxRelay2 = NULL;
lv_obj_t * ui_CheckboxRelay3 = NULL;
lv_obj_t * ui_CheckboxRelay4 = NULL;
lv_obj_t * ui_TabPageTZ = NULL;
lv_obj_t * ui_DropdownTimezone = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_ButtonClose = NULL;
lv_obj_t * ui_Label14 = NULL;
// event funtions
void ui_event_ButtonScan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        doWifiScan(e);
    }
}

void ui_event_TextAreaPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setTextArea(e);
        _ui_screen_change(&ui_ScreenKeyboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenKeyboard_screen_init);
    }
}

void ui_event_ButtonTestConnection(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        doTestConnection(e);
    }
}

void ui_event_TextAreaHost1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setTextArea(e);
        _ui_screen_change(&ui_ScreenKeyboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenKeyboard_screen_init);
    }
}

void ui_event_ButtonTest1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        testHost1(e);
    }
}

void ui_event_TextAreaHost2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setTextArea(e);
        _ui_screen_change(&ui_ScreenKeyboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenKeyboard_screen_init);
    }
}

void ui_event_ButtonTest2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        testHost2(e);
    }
}

void ui_event_TextAreaHost3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setTextArea(e);
        _ui_screen_change(&ui_ScreenKeyboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenKeyboard_screen_init);
    }
}

void ui_event_ButtonTest3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        testHost3(e);
    }
}

void ui_event_CheckboxRelay1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setRelay(e);
    }
}

void ui_event_CheckboxRelay2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setRelay(e);
    }
}

void ui_event_CheckboxRelay3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setRelay(e);
    }
}

void ui_event_CheckboxRelay4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        setRelay(e);
    }
}

void ui_event_ButtonClose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenMain_screen_init);
        savePreferences(e);
    }
}

// build funtions

void ui_ScreenSettings_screen_init(void)
{
    ui_ScreenSettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabViewSettings = lv_tabview_create(ui_ScreenSettings);
    lv_tabview_set_tab_bar_size(ui_TabViewSettings, 50);
    lv_obj_set_width(ui_TabViewSettings, lv_pct(100));
    lv_obj_set_height(ui_TabViewSettings, lv_pct(81));
    lv_obj_set_x(ui_TabViewSettings, 0);
    lv_obj_set_y(ui_TabViewSettings, -21);
    lv_obj_set_align(ui_TabViewSettings, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabViewSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_TabViewSettings, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_tabview_get_tab_bar(ui_TabViewSettings), lv_color_hex(0xDBDCE0),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_bar(ui_TabViewSettings), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPageWifi = lv_tabview_add_tab(ui_TabViewSettings, "WiFi");

    ui_Label1 = lv_label_create(ui_TabPageWifi);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -122);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Password");

    ui_DropdownSSID = lv_dropdown_create(ui_TabPageWifi);
    lv_obj_set_width(ui_DropdownSSID, 184);
    lv_obj_set_height(ui_DropdownSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownSSID, -18);
    lv_obj_set_y(ui_DropdownSSID, -50);
    lv_obj_set_align(ui_DropdownSSID, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownSSID, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label2 = lv_label_create(ui_TabPageWifi);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -140);
    lv_obj_set_y(ui_Label2, -51);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "SSID");

    ui_ButtonScan = lv_button_create(ui_TabPageWifi);
    lv_obj_set_width(ui_ButtonScan, 70);
    lv_obj_set_height(ui_ButtonScan, 40);
    lv_obj_set_x(ui_ButtonScan, 112);
    lv_obj_set_y(ui_ButtonScan, -51);
    lv_obj_set_align(ui_ButtonScan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonScan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonScan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_ButtonScan);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Scan");

    ui_TextAreaPassword = lv_textarea_create(ui_TabPageWifi);
    lv_obj_set_width(ui_TextAreaPassword, 178);
    lv_obj_set_height(ui_TextAreaPassword, 37);
    lv_obj_set_x(ui_TextAreaPassword, 10);
    lv_obj_set_y(ui_TextAreaPassword, 0);
    lv_obj_set_align(ui_TextAreaPassword, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaPassword, "Placeholder...");

    ui_ButtonTestConnection = lv_button_create(ui_TabPageWifi);
    lv_obj_set_width(ui_ButtonTestConnection, 149);
    lv_obj_set_height(ui_ButtonTestConnection, 32);
    lv_obj_set_x(ui_ButtonTestConnection, 0);
    lv_obj_set_y(ui_ButtonTestConnection, 42);
    lv_obj_set_align(ui_ButtonTestConnection, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTestConnection, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonTestConnection, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_ButtonTestConnection);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Test Connection");

    ui_TabPageHosts = lv_tabview_add_tab(ui_TabViewSettings, "Hosts");

    ui_TextAreaHost1 = lv_textarea_create(ui_TabPageHosts);
    lv_obj_set_width(ui_TextAreaHost1, 150);
    lv_obj_set_height(ui_TextAreaHost1, 38);
    lv_obj_set_x(ui_TextAreaHost1, -17);
    lv_obj_set_y(ui_TextAreaHost1, -51);
    lv_obj_set_align(ui_TextAreaHost1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaHost1, "Placeholder...");

    ui_Label5 = lv_label_create(ui_TabPageHosts);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -124);
    lv_obj_set_y(ui_Label5, -51);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Host 1");

    ui_ButtonTest1 = lv_button_create(ui_TabPageHosts);
    lv_obj_set_width(ui_ButtonTest1, 68);
    lv_obj_set_height(ui_ButtonTest1, 33);
    lv_obj_set_x(ui_ButtonTest1, 103);
    lv_obj_set_y(ui_ButtonTest1, -51);
    lv_obj_set_align(ui_ButtonTest1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTest1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonTest1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_ButtonTest1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Test");

    ui_TextAreaHost2 = lv_textarea_create(ui_TabPageHosts);
    lv_obj_set_width(ui_TextAreaHost2, 150);
    lv_obj_set_height(ui_TextAreaHost2, 38);
    lv_obj_set_x(ui_TextAreaHost2, -17);
    lv_obj_set_y(ui_TextAreaHost2, -6);
    lv_obj_set_align(ui_TextAreaHost2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaHost2, "Placeholder...");

    ui_Label7 = lv_label_create(ui_TabPageHosts);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -124);
    lv_obj_set_y(ui_Label7, -6);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Host 2");

    ui_ButtonTest2 = lv_button_create(ui_TabPageHosts);
    lv_obj_set_width(ui_ButtonTest2, 68);
    lv_obj_set_height(ui_ButtonTest2, 33);
    lv_obj_set_x(ui_ButtonTest2, 102);
    lv_obj_set_y(ui_ButtonTest2, -6);
    lv_obj_set_align(ui_ButtonTest2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTest2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonTest2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_ButtonTest2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, -1);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Test");

    ui_Label9 = lv_label_create(ui_TabPageHosts);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -126);
    lv_obj_set_y(ui_Label9, 37);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Host 3");

    ui_TextAreaHost3 = lv_textarea_create(ui_TabPageHosts);
    lv_obj_set_width(ui_TextAreaHost3, 150);
    lv_obj_set_height(ui_TextAreaHost3, 38);
    lv_obj_set_x(ui_TextAreaHost3, -17);
    lv_obj_set_y(ui_TextAreaHost3, 37);
    lv_obj_set_align(ui_TextAreaHost3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaHost3, "Placeholder...");

    ui_ButtonTest3 = lv_button_create(ui_TabPageHosts);
    lv_obj_set_width(ui_ButtonTest3, 68);
    lv_obj_set_height(ui_ButtonTest3, 33);
    lv_obj_set_x(ui_ButtonTest3, 104);
    lv_obj_set_y(ui_ButtonTest3, 37);
    lv_obj_set_align(ui_ButtonTest3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonTest3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonTest3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_ButtonTest3);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Test");

    ui_TabPageActions = lv_tabview_add_tab(ui_TabViewSettings, "Actions");

    ui_Label11 = lv_label_create(ui_TabPageActions);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -98);
    lv_obj_set_y(ui_Label11, -53);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Reboot after ");

    ui_DropdownReboot = lv_dropdown_create(ui_TabPageActions);
    lv_dropdown_set_options(ui_DropdownReboot, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10");
    lv_obj_set_width(ui_DropdownReboot, 57);
    lv_obj_set_height(ui_DropdownReboot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownReboot, -16);
    lv_obj_set_y(ui_DropdownReboot, -53);
    lv_obj_set_align(ui_DropdownReboot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownReboot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label12 = lv_label_create(ui_TabPageActions);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 79);
    lv_obj_set_y(ui_Label12, -53);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "consec failures");

    ui_Label15 = lv_label_create(ui_TabPageActions);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -101);
    lv_obj_set_y(ui_Label15, -9);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Ping every");

    ui_DropdownPing = lv_dropdown_create(ui_TabPageActions);
    lv_dropdown_set_options(ui_DropdownPing, "1\n2\n5\n10\n20\n30");
    lv_obj_set_width(ui_DropdownPing, 57);
    lv_obj_set_height(ui_DropdownPing, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownPing, -16);
    lv_obj_set_y(ui_DropdownPing, -9);
    lv_obj_set_align(ui_DropdownPing, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownPing, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label16 = lv_label_create(ui_TabPageActions);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 56);
    lv_obj_set_y(ui_Label16, -9);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "minutes");

    ui_TabPageTest = lv_tabview_add_tab(ui_TabViewSettings, "Test");

    ui_CheckboxRelay1 = lv_checkbox_create(ui_TabPageTest);
    lv_checkbox_set_text(ui_CheckboxRelay1, "Test Relay 1");
    lv_obj_set_width(ui_CheckboxRelay1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxRelay1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxRelay1, -2);
    lv_obj_set_y(ui_CheckboxRelay1, -49);
    lv_obj_set_align(ui_CheckboxRelay1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxRelay1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_CheckboxRelay2 = lv_checkbox_create(ui_TabPageTest);
    lv_checkbox_set_text(ui_CheckboxRelay2, "Test Relay 2");
    lv_obj_set_width(ui_CheckboxRelay2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxRelay2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxRelay2, 0);
    lv_obj_set_y(ui_CheckboxRelay2, -19);
    lv_obj_set_align(ui_CheckboxRelay2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxRelay2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_CheckboxRelay3 = lv_checkbox_create(ui_TabPageTest);
    lv_checkbox_set_text(ui_CheckboxRelay3, "Test Relay 3");
    lv_obj_set_width(ui_CheckboxRelay3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxRelay3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxRelay3, 0);
    lv_obj_set_y(ui_CheckboxRelay3, 10);
    lv_obj_set_align(ui_CheckboxRelay3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxRelay3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_CheckboxRelay4 = lv_checkbox_create(ui_TabPageTest);
    lv_checkbox_set_text(ui_CheckboxRelay4, "Test Relay 4");
    lv_obj_set_width(ui_CheckboxRelay4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckboxRelay4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckboxRelay4, 0);
    lv_obj_set_y(ui_CheckboxRelay4, 40);
    lv_obj_set_align(ui_CheckboxRelay4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CheckboxRelay4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_TabPageTZ = lv_tabview_add_tab(ui_TabViewSettings, "Timezone");

    ui_DropdownTimezone = lv_dropdown_create(ui_TabPageTZ);
    lv_dropdown_set_options(ui_DropdownTimezone,
                            "GMT\nGMT+1\nGMT+10\nGMT+11\nGMT+12\nGMT+2\nGMT+3\nGMT+4\nGMT+5\nGMT+6\nGMT+7\nGMT+8\nGMT+9\nGMT-1\nGMT-10\nGMT-11\nGMT-12\nGMT-13\nGMT-14\nGMT-2\nGMT-3\nGMT-4\nGMT-5\nGMT-6\nGMT-7\nGMT-8\nGMT-9\nUTC\n");
    lv_obj_set_width(ui_DropdownTimezone, 150);
    lv_obj_set_height(ui_DropdownTimezone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownTimezone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownTimezone, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label17 = lv_label_create(ui_TabPageTZ);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 0);
    lv_obj_set_y(ui_Label17, -41);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Select Timezone:");

    ui_ButtonClose = lv_button_create(ui_ScreenSettings);
    lv_obj_set_width(ui_ButtonClose, 100);
    lv_obj_set_height(ui_ButtonClose, 37);
    lv_obj_set_x(ui_ButtonClose, 2);
    lv_obj_set_y(ui_ButtonClose, 97);
    lv_obj_set_align(ui_ButtonClose, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonClose, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonClose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonClose, lv_color_hex(0x02A89E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonClose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_ButtonClose);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "OK");

    lv_obj_add_event_cb(ui_ButtonScan, ui_event_ButtonScan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaPassword, ui_event_TextAreaPassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonTestConnection, ui_event_ButtonTestConnection, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaHost1, ui_event_TextAreaHost1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonTest1, ui_event_ButtonTest1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaHost2, ui_event_TextAreaHost2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonTest2, ui_event_ButtonTest2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaHost3, ui_event_TextAreaHost3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonTest3, ui_event_ButtonTest3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxRelay1, ui_event_CheckboxRelay1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxRelay2, ui_event_CheckboxRelay2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxRelay3, ui_event_CheckboxRelay3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CheckboxRelay4, ui_event_CheckboxRelay4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonClose, ui_event_ButtonClose, LV_EVENT_ALL, NULL);

}

void ui_ScreenSettings_screen_destroy(void)
{
    if(ui_ScreenSettings) lv_obj_del(ui_ScreenSettings);

    // NULL screen variables
    ui_ScreenSettings = NULL;
    ui_TabViewSettings = NULL;
    ui_TabPageWifi = NULL;
    ui_Label1 = NULL;
    ui_DropdownSSID = NULL;
    ui_Label2 = NULL;
    ui_ButtonScan = NULL;
    ui_Label3 = NULL;
    ui_TextAreaPassword = NULL;
    ui_ButtonTestConnection = NULL;
    ui_Label4 = NULL;
    ui_TabPageHosts = NULL;
    ui_TextAreaHost1 = NULL;
    ui_Label5 = NULL;
    ui_ButtonTest1 = NULL;
    ui_Label6 = NULL;
    ui_TextAreaHost2 = NULL;
    ui_Label7 = NULL;
    ui_ButtonTest2 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;
    ui_TextAreaHost3 = NULL;
    ui_ButtonTest3 = NULL;
    ui_Label10 = NULL;
    ui_TabPageActions = NULL;
    ui_Label11 = NULL;
    ui_DropdownReboot = NULL;
    ui_Label12 = NULL;
    ui_Label15 = NULL;
    ui_DropdownPing = NULL;
    ui_Label16 = NULL;
    ui_TabPageTest = NULL;
    ui_CheckboxRelay1 = NULL;
    ui_CheckboxRelay2 = NULL;
    ui_CheckboxRelay3 = NULL;
    ui_CheckboxRelay4 = NULL;
    ui_TabPageTZ = NULL;
    ui_DropdownTimezone = NULL;
    ui_Label17 = NULL;
    ui_ButtonClose = NULL;
    ui_Label14 = NULL;

}
