// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: PingPuppy

#ifndef UI_SCREENSETTINGS_H
#define UI_SCREENSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSettings
extern void ui_ScreenSettings_screen_init(void);
extern void ui_ScreenSettings_screen_destroy(void);
extern lv_obj_t * ui_ScreenSettings;
extern lv_obj_t * ui_TabViewSettings;
extern lv_obj_t * ui_TabPageWifi;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_DropdownSSID;
extern lv_obj_t * ui_Label2;
extern void ui_event_ButtonScan(lv_event_t * e);
extern lv_obj_t * ui_ButtonScan;
extern lv_obj_t * ui_Label3;
extern void ui_event_TextAreaPassword(lv_event_t * e);
extern lv_obj_t * ui_TextAreaPassword;
extern void ui_event_ButtonTestConnection(lv_event_t * e);
extern lv_obj_t * ui_ButtonTestConnection;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_TabPageHosts;
extern void ui_event_TextAreaHost1(lv_event_t * e);
extern lv_obj_t * ui_TextAreaHost1;
extern lv_obj_t * ui_Label5;
extern void ui_event_ButtonTest1(lv_event_t * e);
extern lv_obj_t * ui_ButtonTest1;
extern lv_obj_t * ui_Label6;
extern void ui_event_TextAreaHost2(lv_event_t * e);
extern lv_obj_t * ui_TextAreaHost2;
extern lv_obj_t * ui_Label7;
extern void ui_event_ButtonTest2(lv_event_t * e);
extern lv_obj_t * ui_ButtonTest2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern void ui_event_TextAreaHost3(lv_event_t * e);
extern lv_obj_t * ui_TextAreaHost3;
extern void ui_event_ButtonTest3(lv_event_t * e);
extern lv_obj_t * ui_ButtonTest3;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_TabPageActions;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_DropdownReboot;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_DropdownPing;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_TabPageTest;
extern void ui_event_CheckboxRelay1(lv_event_t * e);
extern lv_obj_t * ui_CheckboxRelay1;
extern void ui_event_CheckboxRelay2(lv_event_t * e);
extern lv_obj_t * ui_CheckboxRelay2;
extern void ui_event_CheckboxRelay3(lv_event_t * e);
extern lv_obj_t * ui_CheckboxRelay3;
extern void ui_event_CheckboxRelay4(lv_event_t * e);
extern lv_obj_t * ui_CheckboxRelay4;
extern lv_obj_t * ui_TabPageTZ;
extern lv_obj_t * ui_DropdownTimezone;
extern lv_obj_t * ui_Label17;
extern void ui_event_ButtonClose(lv_event_t * e);
extern lv_obj_t * ui_ButtonClose;
extern lv_obj_t * ui_Label14;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label19;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

