// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: PingPuppy

#include "../ui.h"

lv_obj_t * ui_ScreenKeyboard = NULL;
lv_obj_t * ui_KeyboardAlpha = NULL;
lv_obj_t * ui_TextAreaTextValue = NULL;
// event funtions
void ui_event_KeyboardAlpha(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_ScreenSettings_screen_init);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        hideKeyboard(e);
        setTextFromSave(e);
    }
}

// build funtions

void ui_ScreenKeyboard_screen_init(void)
{
    ui_ScreenKeyboard = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenKeyboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KeyboardAlpha = lv_keyboard_create(ui_ScreenKeyboard);
    lv_obj_set_width(ui_KeyboardAlpha, lv_pct(100));
    lv_obj_set_height(ui_KeyboardAlpha, lv_pct(69));
    lv_obj_set_x(ui_KeyboardAlpha, 0);
    lv_obj_set_y(ui_KeyboardAlpha, 34);
    lv_obj_set_align(ui_KeyboardAlpha, LV_ALIGN_CENTER);

    ui_TextAreaTextValue = lv_textarea_create(ui_ScreenKeyboard);
    lv_obj_set_width(ui_TextAreaTextValue, 234);
    lv_obj_set_height(ui_TextAreaTextValue, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_TextAreaTextValue, 0);
    lv_obj_set_y(ui_TextAreaTextValue, -84);
    lv_obj_set_align(ui_TextAreaTextValue, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaTextValue, "Placeholder...");
    lv_textarea_set_one_line(ui_TextAreaTextValue, true);

    lv_keyboard_set_textarea(ui_KeyboardAlpha, ui_TextAreaTextValue);
    lv_obj_add_event_cb(ui_KeyboardAlpha, ui_event_KeyboardAlpha, LV_EVENT_ALL, NULL);

}

void ui_ScreenKeyboard_screen_destroy(void)
{
    if(ui_ScreenKeyboard) lv_obj_del(ui_ScreenKeyboard);

    // NULL screen variables
    ui_ScreenKeyboard = NULL;
    ui_KeyboardAlpha = NULL;
    ui_TextAreaTextValue = NULL;

}
