// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: PingPuppy

#ifndef UI_SCREENKEYBOARD_H
#define UI_SCREENKEYBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenKeyboard
extern void ui_ScreenKeyboard_screen_init(void);
extern void ui_ScreenKeyboard_screen_destroy(void);
extern lv_obj_t * ui_ScreenKeyboard;
extern void ui_event_KeyboardAlpha(lv_event_t * e);
extern lv_obj_t * ui_KeyboardAlpha;
extern lv_obj_t * ui_TextAreaTextValue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

