// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: PingPuppy

#ifndef _PINGPUPPY_UI_H
#define _PINGPUPPY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_ScreenMain.h"
#include "screens/ui_ScreenSettings.h"
#include "screens/ui_ScreenKeyboard.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_pingpuppysmall_png);    // assets/pingpuppysmall.png
LV_IMG_DECLARE(ui_img_wifi1_png);    // assets/wifi1.png
LV_IMG_DECLARE(ui_img_wifi2_png);    // assets/wifi2.png
LV_IMG_DECLARE(ui_img_wifi3_png);    // assets/wifi3.png
LV_IMG_DECLARE(ui_img_wifi4_png);    // assets/wifi4.png
LV_IMG_DECLARE(ui_img_wifi5_png);    // assets/wifi5.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
