// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: PingPuppy

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void doWifiScan(lv_event_t * e);
void setTextArea(lv_event_t * e);
void doTestConnection(lv_event_t * e);
void testHost1(lv_event_t * e);
void testHost2(lv_event_t * e);
void testHost3(lv_event_t * e);
void setRelay(lv_event_t * e);
void savePreferences(lv_event_t * e);
void doCancel(lv_event_t * e);
void hideKeyboard(lv_event_t * e);
void setTextFromSave(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
