// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: PingPuppy

#include "ui.h"
#include <string.h>
#include <WiFi.h>
#include <Preferences.h>

extern bool doSetRelay;
extern int relayIdx;
extern bool relayState;
extern Preferences preferences;
extern char *timeZone;
extern bool validTime;
extern bool isScanning;
extern int failureMode;
extern int pingMinutes;
extern int consecErrorReboot;
extern void loadSettings();

void setRelay(lv_event_t *e)
{

	lv_obj_t *cb = (lv_obj_t *)lv_event_get_target(e);
	if (cb == ui_CheckboxRelay1)
	{
		relayIdx = 0;
	}
	else if (cb == ui_CheckboxRelay2)
	{
		relayIdx = 1;
	}
	else if (cb == ui_CheckboxRelay3)
	{
		relayIdx = 2;
	}
	else if (cb == ui_CheckboxRelay4)
	{
		relayIdx = 3;
	}

	relayState = lv_obj_has_state(cb, LV_STATE_CHECKED);
	doSetRelay = true;
}

static lv_obj_t *ui_TextAreaSave;

void setTextArea(lv_event_t *e)
{
	ui_TextAreaSave = (lv_obj_t *)lv_event_get_target(e);
	lv_textarea_set_text(ui_TextAreaTextValue, lv_textarea_get_text(ui_TextAreaSave));
}

void setTextFromSave(lv_event_t *e)
{
	lv_textarea_set_text(ui_TextAreaSave, lv_textarea_get_text(ui_TextAreaTextValue));
}

void hideKeyboard(lv_event_t *e)
{
	lv_obj_t *kb = (lv_obj_t *)lv_event_get_target(e);
	uint32_t btn_id = lv_keyboard_get_selected_btn(kb);
	const char *txt = lv_keyboard_get_btn_text(kb, btn_id);

	if (strcmp(txt, LV_SYMBOL_NEW_LINE) == 0)
	{
		_ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_ScreenSettings_screen_init);
	}
}

lv_obj_t *mbox1;
static void mbox_event_cb(lv_event_t *e)
{
	lv_msgbox_close(mbox1);
	isScanning = false;
}

void doTestConnection(lv_event_t *e)
{
	isScanning = true;
	String t = "Connecting";
	char ssid[50];
	const char *pass;
	lv_dropdown_get_selected_str(ui_DropdownSSID, ssid, 50);
	pass = lv_textarea_get_text(ui_TextAreaPassword);
	bool status;

	mbox1 = lv_msgbox_create(NULL);
	lv_msgbox_add_title(mbox1, "WiFi Connect");
	lv_obj_t *constr = lv_msgbox_add_text(mbox1, t.c_str());

	WiFi.begin(ssid, pass);
	for (int i = 0; i < 50; i++)
	{
		status = WiFi.isConnected();
		if (status)
		{
			break;
		}
		lv_label_set_text(constr, t.c_str());
		lv_task_handler();
		lv_refr_now(NULL);
		delay(100);
		t += ".";
	}
	lv_msgbox_close(mbox1);
	mbox1 = lv_msgbox_create(NULL);
	lv_msgbox_add_title(mbox1, status ? "Connected!" : "Connect failed.");
	lv_obj_t *btn = lv_msgbox_add_footer_button(mbox1, "OK");
	lv_obj_add_event_cb(btn, mbox_event_cb, LV_EVENT_CLICKED, NULL);
}

void doWifiScan(lv_event_t *e)
{
	isScanning = true;
	lv_dropdown_clear_options(ui_DropdownSSID);
	mbox1 = lv_msgbox_create(NULL);
	lv_obj_t *mt = lv_msgbox_add_text(mbox1, "\nScanning...\n");
	lv_obj_set_align(mt, LV_ALIGN_CENTER);
	lv_task_handler();
	lv_refr_now(NULL);

	WiFi.disconnect();
	byte numSsid = WiFi.scanNetworks();
	for (int thisNet = 0; thisNet < numSsid; thisNet++)
	{
		lv_dropdown_add_option(ui_DropdownSSID, WiFi.SSID(thisNet).c_str(), LV_DROPDOWN_POS_LAST);
	}
	lv_msgbox_close(mbox1);
	isScanning = false;
}

void testHost(String host)
{
	isScanning = true;

	mbox1 = lv_msgbox_create(NULL);
	String t = "Connecting to " + host;
	lv_obj_t *constr = lv_msgbox_add_text(mbox1, t.c_str());

	WiFiClient client;
	bool status = client.connect(host.c_str(), 80);
	if (status)
	{
		t = "Connected to " + host;
	}
	else
	{
		t = "Connection to " + host + " failed.";
	}
	lv_label_set_text(constr, t.c_str());
	lv_task_handler();
	lv_refr_now(NULL);
	lv_obj_t *btn = lv_msgbox_add_footer_button(mbox1, "OK");
	lv_obj_add_event_cb(btn, mbox_event_cb, LV_EVENT_CLICKED, NULL);
}

void testHost1(lv_event_t *e)
{
	testHost(lv_textarea_get_text(ui_TextAreaHost1));
}

void testHost2(lv_event_t *e)
{
	testHost(lv_textarea_get_text(ui_TextAreaHost2));
}

void testHost3(lv_event_t *e)
{
	testHost(lv_textarea_get_text(ui_TextAreaHost3));
}

void savePreferences(lv_event_t *e)
{
	char tchr[50];
	const char *pchr;
	lv_dropdown_get_selected_str(ui_DropdownSSID, tchr, 50);
	pchr = lv_textarea_get_text(ui_TextAreaPassword);
	preferences.putString("SSID", tchr);
	preferences.putString("pwd", pchr);
	pchr = lv_textarea_get_text(ui_TextAreaHost1);
	preferences.putString("host1", pchr);
	pchr = lv_textarea_get_text(ui_TextAreaHost2);
	preferences.putString("host2", pchr);
	pchr = lv_textarea_get_text(ui_TextAreaHost3);
	preferences.putString("host3", pchr);
	lv_dropdown_get_selected_str(ui_DropdownTimezone, tchr, 50);
	strcpy(timeZone, tchr);
	preferences.putString("timezone", timeZone);
	preferences.putInt("pingMinutes", pingMinutes);
	preferences.putInt("rebootCount", consecErrorReboot);
	lv_dropdown_get_selected_str(ui_DropdownPing, tchr, 50);
	pingMinutes = atoi(tchr);
	preferences.putInt("pingMinutes", pingMinutes);
	lv_dropdown_get_selected_str(ui_DropdownReboot, tchr, 50);
	consecErrorReboot = atoi(tchr);
	preferences.putInt("rebootCount", consecErrorReboot);
	validTime = false;
	failureMode = 0;
}
void doCancel(lv_event_t *e)
{
	loadSettings();
}
